language: node_js
node_js:
  - "6"
services: mongodb
before_install:
    - git config --global user.email "zccz14@outlook.com"
    - git config --global user.name "zccz14"
    - npm i -g codeclimate-test-reporter
after_success:
  - cd docs
  - git init
  - git add .
  - git commit -m "Travis Deploy"
  - git push -f -q https://$GITHUB_TOKEN@github.com/zccz14/light.git master:gh-pages
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

